// src/main/index.ts

import { setupDatabase } from '@db/sqlite3'
import { electronApp, is, optimizer } from '@electron-toolkit/utils'
import '@preload/ipc/accounts.ipc'
import '@preload/ipc/ipc'
import { app, BrowserWindow, session, shell } from 'electron'
import path, { join } from 'path'

import { sessionManager } from './session-manager'


function getAppIcon(): string | undefined {
  if (app.isPackaged) {
    // Production - after building with electron-builder
    const resourcesPath = process.resourcesPath
    
    if (process.platform === 'win32') {
      return path.join(resourcesPath, 'icons', 'icon.ico')
    } else if (process.platform === 'darwin') {
      return path.join(resourcesPath, 'icons', 'icon.icns')
    } else if (process.platform === 'linux') {
      return path.join(resourcesPath, 'icons', 'png', '256x256.png')
    }
  } else {
    // Development - using icons generated by electron-icon-builder
    const basePath = path.join(__dirname, '../../build/icons')
    
    if (process.platform === 'win32') {
      return path.join(basePath, 'icon.ico')
    } else if (process.platform === 'darwin') {
      return path.join(basePath, 'icon.icns')
    } else if (process.platform === 'linux') {
      return path.join(basePath, 'png', '256x256.png')
    }
  }
  return undefined
}


async function createWindow(): Promise<void> {
  const mainWindow = new BrowserWindow({
    width: 1024,
    height: 728,
    show: false,
    autoHideMenuBar: true,
    icon: getAppIcon(),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,  // Required to be false for geolocation enabling
      contextIsolation: true,
      nodeIntegration: false
    },
  })

  mainWindow.on('ready-to-show', () => {
    mainWindow.maximize()
    mainWindow.show()
  })

  mainWindow.webContents.setWindowOpenHandler((details) => {
    shell.openExternal(details.url)
    return { action: 'deny' }
  })

  if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    await mainWindow.loadURL(process.env['ELECTRON_RENDERER_URL'])
  } else {
    await mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}


// MAIN APP STARTUP
app.whenReady().then(async () => {
  session.defaultSession.setPermissionRequestHandler(
    (_webContents, permission, callback) => {
      if (permission === 'geolocation') {
        callback(true)
      } else {
        callback(false)
      }
    }
  )

  // Set app name for Windows taskbar
  electronApp.setAppUserModelId('com.plurse.app')

  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })

  try {
    // CRITICAL: Wait for DB + tables + admin user before anything else
    await setupDatabase()
    console.log('Database initialized successfully – tables created, admin user ready')
  } catch (error) {
    console.error('Failed to initialize database:', error)
    app.quit()
    return
  }

  // Only now create the window
  await createWindow()

  // macOS: recreate window when dock icon clicked
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Clean up session on close
app.on('window-all-closed', () => {
  sessionManager.logout()
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('before-quit', () => {
  sessionManager.logout()
})
